---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Enable nginx for amazon linux 2
      shell: "amazon-linux-extras enable nginx1.12"
      become: yes

    - name: Install nginx     # To install nginx .
      yum:
        name: nginx
        state: latest

    - name: Install php
      yum:
        name: '{{item}}'
        state: latest
      with_items:
        - php
        - php-common
        - php-cli
        - php-gd
        - php-curl
        - php-mysql
        - php-fpm
    
    - name: Copy php config files    # To install php.
      copy:
        src: "./files/php.conf"
        dest: "/etc/php-fpm.d/www.conf"
        mode: 0644

    - name: set the right permissions to php directories
      file:
        path: /var/lib/php  
        owner: root
        group: nginx

    - name: Enable php-fpm
      service: name=php-fpm enabled=yes
      become: yes
    
    - name: start php-fpm
      service:
        name: php-fpm
        state: started

    - name: Copy nginx config files
      copy:
        src: "./files/nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        mode: 0644

    - name: Creates directory
      file: 
        path: "/var/www/app"    # creating this directory where placing the application.
        state: directory

    - name: make the build package
      local_action: shell tar -c -z -f app.zip -C ./files/php  # creting zip file out of our Applicaton file. 
      become: no

    # and coping that zip file over ec2 instance then unpack that application ziped package to this directory (/var/www/app) 
    - name: Copy build package
      copy:
        src: "app.zip"
        dest: "/home/ec2-user/app.zip"

    - name: unpack build package
      shell: "tar -xf /home/ec2-user/app.zip -C /var/www/app"
    
    - name: set the right permissions to app directories  # giving write permission to the app directory (/var/www/app)
      file:
        path: /var/www/app
        owner: root
        group: nginx

    - name: Update application nginx config
      copy: 
        src: "./files/application.conf"
        dest: "/etc/nginx/conf.d/app.conf"
        mode: 0644

    - name: Enable Nginx
      service: name=nginx enabled=yes
      become: yes
    
    # finaly, we start the nginx.
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    # setup MariaDB database. 
    - name: Enable mariadb for amazon linux 2
      shell: "amazon-linux-extras enable mariadb10.5"
      become: yes

    # installing MariaDB
    - name: Install mariadb
      yum:
        name: mariadb
        state: latest

    - name: start mariadb
      shell: "systemctl start mariadb"
      become: yes

    - name: enable mariadb service
      shell: "systemctl enable mariadb"
      become: yes

    # creating a database in MairaDB after installation is complete 
    # user_inventory : name of this db. 
    # user_manager : creating a user named (user_manager) to give permission to access db. 
    - name: Recreate database 
      shell:
        cmd: |
          mariadb <<EOF
          DROP USER IF EXISTS user_manager;
          DROP DATABASE IF EXISTS user_inventory;
          CREATE DATABASE user_inventory;
          CREATE USER user_manager IDENTIFIED BY 'Qwerty123';
          GRANT ALL PRIVILEGES ON user_inventory.* TO user_manager;
          EOF
    - name: Copy DB DDL file
      copy:
        src: "./files/user_management.sql"
        dest: "/home/ec2-user/user_management.sql"
        mode: 0644
    - name: Build database tables   #  building tabel for database. 
      shell: "mariadb user_inventory < /home/ec2-user/user_management.sql"
